version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: server local
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs/:/app/plugins/
    # works around "Unable to create JFR repository directory using base
    # location (/tmp)" on some hosts, see kestra-io/kestra#17405
    tmpfs:
      - /tmp
